[package]
name = "scripts"
version = "1.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
thiserror = "1.0.39"
regex = "1.8.3"
open = "4.0.0"
args = { path="../args" }

